config/routes.rb
Rails.application.routes.draw do
  resources :relations
  devise_for :users
  
  resources :users do
  	resources :tweets
  end

  # resources :friendships
  resources :tweets do
  	resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relation.rb
class Relation < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :relations
  has_many :friends, :through => :relations

  has_many :inverse_relations, :class_name => "Relation", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_relations, :source => :user

  # has_many :friendships
  # has_many :friends, :through => :friendships

  has_attached_file :photo , styles: { medium: "300x300>", thumb: "100x100>" ,large: "500x500>"}, default_url: "/home/webwerks1/Images"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    # binding.pry
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.new(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to tweet_path(@tweet), notice: 'User was successfully comment.' }
      else
        format.html { redirect_to tweet_path(@tweet),  notice: 'comment can not be blank!!.'}
      end
    end
  end


  def destroy
    binding.pry
    @tweet = Tweet.find(params[:id])
    @tweet.destroy 
     respond_to do |format|
      format.html { redirect_to tweets_path, notice: 'tweet successfully Deleted.' }
      format.js { render :layout => false ,notice: 'tweet successfully Deleted.' }
    end
  end

   private
    def comment_params
      params.require(:comment).permit(:comment_body, :user_id, :tweet_id)
    end
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  def create
  @relation = current_user.relations.build(:friend_id => params[:friend_id])
  if @relation.save
    flash[:notice] = "Added friend."
    redirect_to root_url
  else
    flash[:error] = "Unable to add friend."
    redirect_to root_url
  end
end


def destroy
  @relation = current_user.relations.find(params[:id])
  @relation.destroy
  flash[:notice] = "Removed friendship."
  redirect_to current_user
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relation
      @relation = Relation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relation_params
      params.require(:relation).permit(:user_id, :friend_id)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
    
  end

	 def show
    	# @user = User.find(params[:user_id])
    	# binding.pry
    	@tweet = Tweet.find(params[:id])
  	end


  	def create
	    @user = User.find(params[:user_id])
	    @tweet = @user.tweets.create(tweet_params)
	    redirect_to user_path(@user)
  	end

  	def destroy
      @tweet = Tweet.find(params[:id])
      @tweet.destroy 
       respond_to do |format|
        format.html { redirect_to tweets_path, notice: 'tweet successfully Deleted.' }
        format.js { render :layout => false ,notice: 'tweet successfully Deleted.' }
      end
    end

  private
   # def set_tweet
   #    @tweet = Tweet.find(params[:id])
   #  end


  def tweet_params
      params.require(:tweet).permit(:tweet_body, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @tweets = Tweet.all
    # binding.pry
    friend_ids = current_user.relations.map(&:friend_id)
    @friend_tweet= Tweet.where(user_id: friend_ids)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # @tweet = @users.tweets.all
        @tweets = Tweet.all

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
     def user_params
      params.require(:user).permit(:name, :email, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterDemo</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: rgb(134, 214, 218)">
  <header >
  <div id="user_nav" class="pull-right" style="background-color: #79589f;">
	  <% if user_signed_in? %>
	    Signed in as <strong><%= current_user.name %></strong>
       <button type="button" class="btn btn-danger">
        <span class="glyphicon glyphicon-play"></span> 
	     <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :style=> "color: white;" %>
      </button>
	  <% else %>
     <button type="button" class="btn btn-info">
        <span class="glyphicon glyphicon-play"></span> 
	     <%= link_to "Sign up", new_user_registration_path %></button> or 
       <button type="button" class="btn btn-success">
        <span class="glyphicon glyphicon-arrow-left"></span>
        <%= link_to "sign in", new_user_session_path %>
       </button>
      
	  <% end %>
  </div>
    </header>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/relations/_form.html.erb
<%= form_with(model: relation, local: true) do |form| %>
  <% if relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(relation.errors.count, "error") %> prohibited this relation from being saved:</h2>

      <ul>
      <% relation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :relation_user_id %>
  </div>

  <div class="field">
    <%= form.label :friend_id %>
    <%= form.number_field :friend_id, id: :relation_friend_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/relations/edit.html.erb
<h1>Editing Relation</h1>

<%= render 'form', relation: @relation %>

<%= link_to 'Show', @relation %> |
<%= link_to 'Back', relations_path %>

app/views/relations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relations.each do |relation| %>
      <tr>
        <td><%= relation.user_id %></td>
        <td><%= relation.friend_id %></td>
        <td><%= link_to 'Show', relation %></td>
        <td><%= link_to 'Edit', edit_relation_path(relation) %></td>
        <td><%= link_to 'Destroy', relation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relation', new_relation_path %>

app/views/relations/new.html.erb
<h1>New Relation</h1>

<%= render 'form', relation: @relation %>

<%= link_to 'Back', relations_path %>

app/views/relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @relation.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @relation.friend_id %>
</p>

<%= link_to 'Edit', edit_relation_path(@relation) %> |
<%= link_to 'Back', relations_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container main-block">
  <div class="container col-sm-6 panel panel-info tweet-info">
    <h1>Tweet:</h1>
      <div class="panel-heading">
    <p>
      <strong>Tweet body:</strong>
      <h3><%= @tweet.tweet_body %></h3>
    </p>
    </div>
    <div class="panel-body">
      <p>
        <strong>User:</strong>
        <%= @tweet.user.name %>
      </p>
    </div>

    <div class="panel-body">
      <p><%= time_ago_in_words(@tweet.created_at) %> ago</p>
    </div>
  
    <button type="button" class="btn btn-info">
      <span class="glyphicon glyphicon-arrow-left"></span>  
      <%= link_to 'Back', user_path(@tweet.user_id) %>
    </button>
  </div>

  <div class="container col-sm-6 panel panel-info commentss">
    <% @tweet.comments.order("created_at desc").each do |c| %>
      <% if c.comment_body.present? %>
        <div class="container comment_each" >
          <p>
            <strong>Comment:</strong>
            <%= c.comment_body %>
          </p>

          <!-- <div><%= link_to 'Delete', tweet_comment_path(c),
                       method: :delete, 
                       data: { confirm: 'Are you sure?'} %></div> -->
        </div>
      <% end %>

    <% end %>
  </div>

  <div class="container col-sm-6 panel panel-info comments" style="height: 100%;">
    <p>Enter Your Comment Here</p>
    <%= form_for [@tweet, @tweet.comments.build] do |f| %>
      <div style="margin-top: 13px;">
        <%= f.text_area :comment_body, cols: "70", rows: "3" %>
      </div>
      <button type="button" class="btn btn-info">
        <span class="glyphicon glyphicon-ok"></span>  
          <%= f.submit "Comment", :class=>"btn btn-info" %>
      </button>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="container">Users</h1>
<div class="container col-sm-6">
  <table>
    <thead>
      <tr class="panel panel-heading">
        <!-- <th>Photo</th><th></th> -->
        <th>Name</th><th></th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>

    </thead>

    <tbody class="panel-body">

      <!-- <p>    <strong>All Users Other Than You</strong></p> -->
      <% @users.each do |user| %>
        <% if user.id != current_user.id %>
          <tr>
          <%# image_tag user.photo.url(:thumb) %>
            <td><%= user.name %></td><td></td>
            <td><%= user.email %></td>
            <td><button class="btn btn-success navbar-btn">
              <%= link_to 'Show', user, :style=>"color: white;" %></td></button>
            <td><button class="btn btn-info navbar-btn">
                  <%= link_to 'Edit', edit_user_path(user), :style=>"color: white;" %>
                  </button>
            </td>
            <!-- <td>
            <!-- <button class="btn btn-danger navbar-btn"> -->
            <%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :style=>"color: white;"  %><!-- </button> -->
            <!-- </td> -->
            <td>
              <button class="btn btn-success navbar-btn">
                <%= link_to "Add Friend", relations_path(:friend_id => user), :method => :post%>
              </button>
            </td>
          </tr>
          <% else %>
          <button class="btn btn-success navbar-btn">
            <%= link_to 'Your Profile', user, :style=>"color: white;" %></td></button>
          <button class="btn btn-info navbar-btn">
            <%= link_to 'Edit', edit_user_path(user), :style=>"color: white;" %>
          </button>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>


<!-- Tweet by all users  -->
<div class="container col-sm-6 panel panel-info tweets">
  <strong>All Tweets By People you follow</strong>
  <% @friend_tweet.order("created_at desc").each do |t| %>
    <%# binding.pry %>
    <%# if t.user_id != current_user.id %>
      <div class="container tweet_each" >
         <strong>Tweet by :</strong>
          <%= t.user.name %>
        <p style="margin-top: 15px;"> 
          <strong>Tweet:</strong>
          <%= t.tweet_body %>
        </p>
        <P>
          Posted <%= time_ago_in_words(t.created_at) %> ago

        </P>
        <p>
        <%# binding.pry %>
        <button type="button" class="btn btn-info">
          <span class="glyphicon glyphicon-eye-open"></span> 
            <%= link_to 'show', user_tweet_path(t.user_id, t.id) %>
        </button>
        <% if current_user.id == t.user_id %>
          <button type="button" class="btn btn-warning">
            <span class="glyphicon glyphicon-eye-open"></span> 
              <%= link_to 'Delete', user_tweet_path(t.user_id, t.id), 
                              :method => :delete, 
                              data: {confirm: "Are you sure?"},remote: true%>
          </button>
        <% end %>
      </p>
    </div>
  <% end %>
</div>


<!-- <button class="btn btn-danger navbar-btn"> -->
<%#= link_to 'New User', new_user_path, :style=>"color: white;" %>
<!-- </button> -->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container main-block">
  <div class="container col-sm-6 panel panel-info user-info">
    <div>
      <h4>Your Twitter Profile</h4>
      <div class="panel-heading">
        <p>
          <%= image_tag @user.photo.url(:medium) %>
        </p>
          <strong>Name:</strong>
          <h2><%= @user.name %></h2>
        </p>
      </div>
      <div class="panel-body">
        <p><strong>Email:</strong>
           <h4><%= @user.email %></h4>
        </p>
      </div>
      <button type="button" class="btn btn-success">
        <span class="glyphicon glyphicon-pencil"></span>
          <%= link_to 'Edit', edit_user_path(@user) %>
      </button>
      <button type="button" class="btn btn-info">
        <span class="glyphicon glyphicon-arrow-left"></span>        
          <%= link_to 'Back', users_path %>
      </button>
    </div>

    <div>
      <h2>Following</h2>
      <ul>
        <% for relation in @user.relations %>
          <li>
            <%=h relation.friend.name %>
            (<%= link_to "remove", relation, :method => :delete %>)
          </li>
        <% end %>
      </ul>


      <p>
        <% if current_user.id == @user.id %>
         <%= link_to "Find Friends", users_path %></p>
        <% end %>
      <h2>Followers</h2>
      <ul>
        <% for user in @user.inverse_friends %>
          <li><%=h user.name %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="container col-sm-6 panel panel-info tweets">
    <%= form_for([@user, @user.tweets.build]) do |form| %>
      <% if current_user.id == @user.id %>
        <%= form.label :Tweet_here %>
        <%= form.text_area :tweet_body, cols: "75", rows: "3" %>
        <p>
          <button type="button" class="btn btn-info">
            <span class="glyphicon glyphicon-ok"></span>  
            <%= form.submit :class=>"btn btn-info" %>
          </button>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="container col-sm-6 panel panel-info tweets">
    <strong>Tweets by <%= @user.name %></strong>
    <% @user.tweets.order("created_at desc").each do |t| %>
      <% if t.tweet_body.present? %>
        <div class="container tweet_each" >
          <p style="margin-top: 15px;"> 
            <strong>Tweet:</strong>
            <%= t.tweet_body %>
          </p>
          <p>
            Posted <%= time_ago_in_words(t.created_at) %> ago
          </p>
          <p>
          <%# binding.pry %>
          <button type="button" class="btn btn-info">
            <span class="glyphicon glyphicon-eye-open"></span> 
              <%= link_to 'show', user_tweet_path(t.user_id, t.id) %>
          </button>
          <% if current_user.id == @user.id %>
            <button type="button" class="btn btn-warning">
              <span class="glyphicon glyphicon-eye-open"></span> 
                <%= link_to 'Delete', user_tweet_path(t.user_id, t.id), 
                              :method => :delete, 
                              data: {confirm: "Are you sure?"},remote: true%>
            </button>
            <% end %>
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>